# This is a basic workflow to help you get started with Actions

name: Build BPI-M2Z-bsp

permissions:
  contents: write

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  # push:
  #   branches: [ "master" ]
  #   paths:   # 这里是用来指定哪个文件更改，才会触发的
  #     - '.github/workflows/build-bpi-m2z-bsp.yml'
#   pull_request:
#     branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test scenario tags'


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Build-BPI-M2Z-bsp:
    runs-on: ubuntu-20.04
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '2.7' 
      - name: Git clone and build
        run: |
          sudo apt-get install tree
          sudo apt-get install u-boot-tools
          git clone https://github.com/BPI-SINOVOIP/BPI-M2Z-bsp.git
          cd BPI-M2Z-bsp
          ./build.sh BPI-M2Z-720P 1
          echo ls `pwd`
          ls
          echo tree `pwd`
          tree | tee tree.txt
          cd ..
        
      - name: Get current date
        id: date
        # run: echo "::set-output name=date::$(date +'%Y-%m-%d %H:%M:%S')"
        run: echo "date=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT

      - name: Release   
        uses: softprops/action-gh-release@v1
        # if: startsWith(github.ref, 'refs/tags/')
        with: 
          tag_name: bpi-m2z-bsp-${{ steps.date.outputs.date }}
          name: Release BPI-M2Z-bsp ${{ steps.date.outputs.date }}
          files: |
            BPI-M2Z-bsp/out/100MB/*
            BPI-M2Z-bsp/tree.txt