# This is a basic workflow to help you get started with Actions

name: Build BPI-M2Z-bsp

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
    paths:   # 这里是用来指定哪个文件更改，才会触发的
      - '.github/workflows/build-bpi-m2z-bsp.yml'
#   pull_request:
#     branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test scenario tags'


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_bpi_m2z:
    runs-on: ubuntu-20.04
    
    steps:
      - uses: actions/checkout@v3
          
      - name: Build BPI-M2Z-bsp
        run: |
          sudo apt-get install u-boot-tools
          git clone -b tghul-patch-1 git@github.com:tghul/BPI-M2P-bsp-4.4.git
          cd BPI-M2P-bsp-4.4
          ./build.sh BPI-M2Z-720P 1
        

      # - uses: actions/upload-artifact@v3.1.2
      #   with:
      #     name: BPI-M2Z-720P-linux4.4-8k.img
      #     path: BPI-M2Z-720P-linux4.4-8k.img.gz
      - name: Release   
        uses: softprops/action-gh-release@v1
        # if: startsWith(github.ref, 'refs/tags/')
        with: 
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}
          files: BPI-M2Z-720P-linux4.4-8k.img.gz
